USE PRACTICA
GO

CREATE PROC CONSULTAR_TIPOPERSONA
AS
SELECT * FROM TIPOPERSONA


CREATE PROC AGREGAR_TIPOPERSONA
@ID BIGINT,
@NOMBRE NVARCHAR(50)
AS
INSERT INTO TIPOPERSONA VALUES (@NOMBRE)

CREATE PROC ELIMINAR_TIPOPERSONA
@ID BIGINT 
AS
DELETE FROM TIPOPERSONA WHERE ID=@ID

CREATE PROC MODIFICAR_TIPOPERSONA
@ID BIGINT,
@NOMBRE NVARCHAR(50)
AS
UPDATE TIPOPERSONA SET NOMBRE= @NOMBRE WHERE ID=@ID;

////////////////////////////////////
CREATE PROC CONSULTAR_PERSONA
AS
SELECT * FROM PERSONA

CREATE PROC AGREGAR_PERSONA
@NOMBRES NVARCHAR(50),
@APELLIDOS NVARCHAR(50),
@IDTIPOPERSONA BIGINT
AS
INSERT INTO PERSONA VALUES (@NOMBRES,@APELLIDOS,@IDTIPOPERSONA)

CREATE PROC ELIMINAR_PERSONA
@ID BIGINT 
AS
DELETE FROM PERSONA WHERE ID=@ID

CREATE PROC MODIFICAR_PERSONA
@ID BIGINT,
@NOMBRES NVARCHAR(50),
@APELLIDOS NVARCHAR(50),
@IDTIPOPERSONA BIGINT
AS
UPDATE TIPOPERSONA SET @NOMBRES= @NOMBRES, @APELLIDOS= @APELLIDOS, @IDTIPOPERSONA =@IDTIPOPERSONA WHERE ID=@ID;

///////////////////////////////////////////////

CREATE PROC CONSULTAR_MODULOS
AS
SELECT * FROM MODULOS


CREATE PROC AGREGAR_MODULOS
@ID BIGINT,
@NOMBRE NVARCHAR(50),
@IDPERSONA BIGINT
AS
INSERT INTO MODULOS VALUES (@NOMBRE)

CREATE PROC ELIMINAR_MODULOS
@ID BIGINT 
AS
DELETE FROM MODULOS WHERE ID=@ID

CREATE PROC MODIFICAR_MODULOS
@ID BIGINT,
@NOMBRE NVARCHAR(50),
@IDPERSONA BIGINT
AS
UPDATE MODULOS SET NOMBRE= @NOMBRE WHERE ID=@ID;