CREATE DATABASE PRACTICA
GO


CREATE TABLE TIPOPERSONA(
ID BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NOMBRE NVARCHAR(50) NOT NULL
);

CREATE TABLE PERSONA(
ID BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NOMBRES NVARCHAR(50) NOT NULL,
APELLIDOS NVARCHAR(50) NOT NULL,
IDTIPOPERSONA BIGINT FOREIGN KEY REFERENCES TIPOPERSONA (ID)
);

CREATE TABLE MODULOS(
ID BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NOMBRE NVARCHAR(50),
IDPERSONA BIGINT FOREIGN KEY REFERENCES PERSONA (ID)
);

CREATE TABLE ASIGNACIONDEMODULO (
ID BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
IDMODULOS BIGINT FOREIGN KEY REFERENCES MODULOS (ID),
FECHAREGISTRO DATETIME
);
